CREATE TABLE employee_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    CONSTRAINT fk_employee_invitations_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT uk_employee_invitations_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_employee_invitations_status
        CHECK (status IN ('PENDING', 'USED', 'REVOKED', 'EXPIRED'))
);

CREATE UNIQUE INDEX uk_employee_invitations_pending_employee
    ON employee_invitations (employee_id)
    WHERE status = 'PENDING';

CREATE INDEX idx_employee_invitations_employee
    ON employee_invitations (employee_id);
