CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    assigned_employee_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    time_allowed_minutes INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    progress INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMPTZ,
    deadline TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_tasks_assigned_employee FOREIGN KEY (assigned_employee_id) REFERENCES employees(id),
    CONSTRAINT fk_tasks_created_by_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_tasks_title_not_blank CHECK (BTRIM(title) <> ''),
    CONSTRAINT chk_tasks_time_allowed_positive CHECK (time_allowed_minutes > 0),
    CONSTRAINT chk_tasks_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'DECLINED', 'COMPLETED')),
    CONSTRAINT chk_tasks_progress_range CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_tasks_deadline_order CHECK (deadline IS NULL OR accepted_at IS NULL OR deadline >= accepted_at),
    CONSTRAINT chk_tasks_completed_order CHECK (completed_at IS NULL OR accepted_at IS NULL OR completed_at >= accepted_at),
    CONSTRAINT chk_tasks_status_fields CHECK (
        (status = 'PENDING' AND progress = 0 AND accepted_at IS NULL AND deadline IS NULL AND completed_at IS NULL)
        OR (status = 'IN_PROGRESS' AND progress BETWEEN 0 AND 99 AND accepted_at IS NOT NULL AND deadline IS NOT NULL AND completed_at IS NULL)
        OR (status = 'DECLINED' AND progress = 0 AND accepted_at IS NULL AND deadline IS NULL AND completed_at IS NULL)
        OR (status = 'COMPLETED' AND progress = 100 AND accepted_at IS NOT NULL AND deadline IS NOT NULL AND completed_at IS NOT NULL)
    )
);

CREATE INDEX idx_tasks_assigned_employee_id ON tasks (assigned_employee_id);
CREATE INDEX idx_tasks_created_by_user_id ON tasks (created_by_user_id);
CREATE INDEX idx_tasks_assigned_employee_status ON tasks (assigned_employee_id, status);
CREATE INDEX idx_tasks_created_by_user_status ON tasks (created_by_user_id, status);
