CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    CONSTRAINT fk_notifications_recipient_user FOREIGN KEY (recipient_user_id) REFERENCES users(id),
    CONSTRAINT fk_notifications_task FOREIGN KEY (task_id) REFERENCES tasks(id),
    CONSTRAINT chk_notifications_type CHECK (type IN ('TASK_ASSIGNED', 'TASK_ACCEPTED', 'TASK_DECLINED')),
    CONSTRAINT chk_notifications_message_not_blank CHECK (BTRIM(message) <> '')
);

CREATE INDEX idx_notifications_recipient_created_at
    ON notifications (recipient_user_id, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_user_id, read_at)
    WHERE read_at IS NULL;
