CREATE TABLE task_checklist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    description TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_task_checklist_items_task
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT chk_task_checklist_items_description_not_blank
        CHECK (BTRIM(description) <> ''),
    CONSTRAINT chk_task_checklist_items_completed_at
        CHECK (
            (completed = FALSE AND completed_at IS NULL)
            OR (completed = TRUE AND completed_at IS NOT NULL)
        )
);

CREATE INDEX idx_task_checklist_items_task_id
    ON task_checklist_items (task_id);
