CREATE TABLE task_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    uploader_user_id BIGINT NOT NULL,
    attachment_type VARCHAR(30) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL UNIQUE,
    content_type VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_task_attachments_task
        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_task_attachments_uploader
        FOREIGN KEY (uploader_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_task_attachments_type
        CHECK (attachment_type IN ('ADMIN_RESOURCE', 'EMPLOYEE_SUBMISSION')),
    CONSTRAINT chk_task_attachments_file_size
        CHECK (file_size > 0)
);

CREATE INDEX idx_task_attachments_task_id ON task_attachments(task_id);
