CREATE TABLE task_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    activity_type VARCHAR(30) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_activities_task FOREIGN KEY (task_id) REFERENCES tasks(id),
    CONSTRAINT fk_task_activities_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id),
    CONSTRAINT chk_task_activities_type CHECK (activity_type IN (
        'TASK_CREATED', 'TASK_ACCEPTED', 'TASK_DECLINED', 'TASK_UPDATED',
        'CHECKLIST_UPDATED', 'PROGRESS_UPDATED', 'ATTACHMENT_UPLOADED',
        'TASK_COMPLETED', 'TASK_ARCHIVED'
    )),
    CONSTRAINT chk_task_activities_message_not_blank CHECK (BTRIM(message) <> '')
);

CREATE INDEX idx_task_activities_task_created_at
    ON task_activities (task_id, created_at, id);
