CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_departments_name UNIQUE (name)
);

CREATE UNIQUE INDEX uk_departments_name_case_insensitive
    ON departments (LOWER(name));

INSERT INTO departments (name)
SELECT MIN(normalized_name)
FROM (
    SELECT CASE
        WHEN BTRIM(department) = '' THEN 'Unassigned'
        ELSE BTRIM(department)
    END AS normalized_name
    FROM employees
) existing_departments
GROUP BY LOWER(normalized_name);

ALTER TABLE employees
    ADD COLUMN department_id BIGINT;

UPDATE employees e
SET department_id = d.id
FROM departments d
WHERE LOWER(d.name) = LOWER(
    CASE
        WHEN BTRIM(e.department) = '' THEN 'Unassigned'
        ELSE BTRIM(e.department)
    END
);

ALTER TABLE employees
    ALTER COLUMN department_id SET NOT NULL,
    ADD CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE employees
    DROP COLUMN department;