ALTER TABLE users
    ADD COLUMN employee_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT uk_users_employee_id UNIQUE (employee_id),
    ADD CONSTRAINT fk_users_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
        ON DELETE SET NULL;

CREATE TABLE work_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    CONSTRAINT fk_work_shifts_employee
        FOREIGN KEY (employee_id) REFERENCES employees(id)
        ON DELETE CASCADE,
    CONSTRAINT chk_work_shifts_time_order
        CHECK (end_time IS NULL OR end_time >= start_time)
);

CREATE INDEX idx_work_shifts_employee_id
    ON work_shifts (employee_id);