CREATE TABLE registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_registration_requests_status
        CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE UNIQUE INDEX uk_registration_requests_pending_username
    ON registration_requests (LOWER(username))
    WHERE status = 'PENDING';

CREATE UNIQUE INDEX uk_registration_requests_pending_email
    ON registration_requests (LOWER(email))
    WHERE status = 'PENDING';

CREATE INDEX idx_registration_requests_status_created_at
    ON registration_requests (status, created_at);
